# Porta
server.port=9090

# Banco de Dados Local
spring.datasource.url=jdbc:postgresql://localhost:5432/objectstorage
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.default_schema=garage
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.show-sql=true

# S3 / Garage
aws.s3.endpoint=http://garage:3900
aws.s3.access-key=SEU_ACCESS_KEY
aws.s3.secret-key=SEU_SECRET_KEY
aws.s3.bucket=meu-bucket
aws.s3.region=us-east-1