# Porta
server.port=9090

# Banco de Dados Local
spring.datasource.url=jdbc:postgresql://localhost:5432/objectstorage
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.default_schema=garage
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.show-sql=true

# S3 / Garage
#Porta da API S3 docker-compose/garage.toml
aws.s3.endpoint=http://localhost:3900
#Key ID
aws.s3.access-key=GK8c57c6590d47e38cda2f99c3
#Secret Key
aws.s3.secret-key=436355834f9946ae0985729b2afd68f923798a894725f54457b3e53a0d39068a
#Bucket
aws.s3.bucket=sgt-bucket

aws.s3.region=garage

# Limite de Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB