# Porta
server.port=9090

# Banco de Dados Local
spring.datasource.url=jdbc:postgresql://localhost:5432/objectstorage
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.default_schema=garage
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.show-sql=true